- name: java - add repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "ppa:webupd8team/java"

- name: java - accept license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: java - install
  apt:
    name: "oracle-java8-installer"
    state: present